### ISSUE TITLE
Error when running "pub global run rpi_spi:build_lib"

### ISSUE THREAD

**Issue by vinicentus** [danrubel/rpi_spi.dart#1]
When trying to run `pub global run rpi_spi:build_lib` I get the following error:

> Dart VM... /usr/lib/dart-sdk/bin/dart
Dart SDK... /usr/lib/dart-sdk
Cannot find rpi_spi in pub list result
Must run this script on app referencing rpi_spi package
Unhandled exception:
Aborting build
#0      assertNoPubListError (file:///home/pi/.pub-cache/hosted/pub.dartlang.org/rpi_spi-0.1.1/bin/build_lib.dart:82:7)
#1      main (file:///home/pi/.pub-cache/hosted/pub.dartlang.org/rpi_spi-0.1.1/bin/build_lib.dart:32:3)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

@danrubel any idea of what might be causing this and how to fix it?

**Comment by vinicentus** [comment]
Never mind. I just didn't import the package correctly. Issue solved.

**Comment by danrubel** [comment]
Glad you got it working. Please let me know any suggestions you have for better error message wording or bugs you run into when using the package. Thanks!
