### ISSUE TITLE
Can we get an Update to Pub.dev

### ISSUE THREAD

**Issue by BuddhiAbeyratne** [danrubel/rpi_spi.dart#2]
Hey maintainers, 
While looking for an SPI package and came across yours.
but the health seems unnecessarily low due to pub.dev not being updated. 
can we get it updated if we push a pr with some of the recommended fixes?

**Comment by danrubel** [comment]
Just published version 0.1.2 with various cleanups.
If there's a particular chip you'd like to see supported, please open a new issue and I'll see what I can do.

**Comment by danrubel** [comment]
Also, If you have a bug fix you need or an enhancement you'd like to make, PRs are most welcome.
