### ISSUE TITLE
Builds fine but won't run

### ISSUE THREAD

**Issue by tpevahouse25** [danrubel/rpi_spi.dart#3]
I am trying to use the package to communicate with a LoRa chip. 
I ran these 2 commands from the command line on the raspberry pi:
pub global activate rpi_spi
pub global run rpi_spi:build_native

They did not throw any errors. 

I then built the bundle using "flutter build bundle" and it compiled successfully. 

Then when i run the bundle i get these errors: 
[ERROR:engine/src/flutter/shell/common/shell.cc(103)] Dart Error: Unknown library tag.error: library handler failed
[ERROR:engine/src/flutter/runtime/dart_isolate.cc(171)] Could not prepare isolate.
[ERROR:engine/src/flutter/runtime/runtime_controller.cc(415)] Could not create root isolate.
[ERROR:engine/src/flutter/shell/common/shell.cc(588)] Could not launch engine with configuration.

It did run successfully before I added the include for rpi_spi.

Are there any suggestions on what I should do to fix this. 
Thanks.

**Comment by danrubel** [comment]
It is designed to be used with Dart and I have not tried using it with Flutter.
Flutter is built on Dart, but may have some restrictions preventing it from functioning... not sure.

I suggest copying the example code (https://github.com/danrubel/rpi_spi.dart/blob/master/example/example.dart)
then modify it to communicate with the LoRa chip.
Get it running using just Dart from the command line.
Once that is working, try enhancing it then integrating it into your Flutter application.

What are the specs for the LoRa chip?
And how are you connecting it to the Raspberry Pi?
I'm interested in checking it out and maybe there's some way I can investigate/help.

**Comment by danrubel** [comment]
This package has been updated to use `dart:ffi` and now runs on Dart SDK 2.18.
Please let me know if that helps.

**Comment by tpevahouse25** [comment]
Sorry I didn't respond earlier about this. I decided to go a different route with my project. Then I later tried this library again to find out that I needed to install the library directly on the raspberry pi using apt package installer. It does work with a flutter application using flutter-pi.

**Comment by danrubel** [comment]
Good to know. Please re-open this issue or open a new issue if there is something additional I can address.
